/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentreport;

/**
 *
 * @author Naruto
 */
public class Account_section extends javax.swing.JFrame {

    /**
     * Creates new form Account_section
     */
    public Account_section() {
        initComponents();
        setLocation(650,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editstud = new javax.swing.JButton();
        adminbtn2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        duefees = new javax.swing.JButton();
        viewstud = new javax.swing.JButton();
        adminbtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 207, 184));

        editstud.setBackground(new java.awt.Color(195, 155, 116));
        editstud.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        editstud.setForeground(new java.awt.Color(51, 51, 51));
        editstud.setText("Edit Student");
        editstud.setFocusPainted(false);
        editstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editstudActionPerformed(evt);
            }
        });

        adminbtn2.setBackground(new java.awt.Color(195, 155, 116));
        adminbtn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        adminbtn2.setForeground(new java.awt.Color(51, 51, 51));
        adminbtn2.setText("Add Student");
        adminbtn2.setFocusPainted(false);
        adminbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(237, 226, 214));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 53, 25));
        jLabel2.setText("Account Section");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        duefees.setBackground(new java.awt.Color(195, 155, 116));
        duefees.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        duefees.setForeground(new java.awt.Color(51, 51, 51));
        duefees.setText("Due Fees");
        duefees.setFocusPainted(false);
        duefees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duefeesActionPerformed(evt);
            }
        });

        viewstud.setBackground(new java.awt.Color(195, 155, 116));
        viewstud.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        viewstud.setForeground(new java.awt.Color(51, 51, 51));
        viewstud.setText("View Student");
        viewstud.setFocusPainted(false);
        viewstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstudActionPerformed(evt);
            }
        });

        adminbtn4.setBackground(new java.awt.Color(178, 220, 230));
        adminbtn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        adminbtn4.setForeground(new java.awt.Color(51, 51, 51));
        adminbtn4.setText("Logout");
        adminbtn4.setFocusPainted(false);
        adminbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewstud, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duefees, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editstud, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(adminbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(viewstud, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(editstud, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(duefees, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(adminbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editstudActionPerformed
        edit_student es=new edit_student();

        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editstudActionPerformed

    private void adminbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn2ActionPerformed
        
        add_student as=new add_student();
        as.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminbtn2ActionPerformed

    private void duefeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duefeesActionPerformed
        // TODO add your handling code here:
        stud_dueFees sd=new stud_dueFees();
        sd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_duefeesActionPerformed

    private void viewstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstudActionPerformed
        // TODO add your handling code here:
        view_student vs=new view_student();
        vs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewstudActionPerformed

    private void adminbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtn4ActionPerformed
        // TODO add your handling code here:
        MainFrame sr=new MainFrame();
        sr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminbtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn2;
    private javax.swing.JButton adminbtn4;
    private javax.swing.JButton duefees;
    private javax.swing.JButton editstud;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewstud;
    // End of variables declaration//GEN-END:variables
}
